% From https://github.com/UWIT-IAM/UWThesis

\documentclass [11pt, proquest] {uwthesis}[2015/03/03]


% fix for pandoc 1.14
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}

\newtheorem{theorem}{Jibberish}

%% \bibliography{references}

\hyphenation{mar-gin-al-ia}

%
% ----- apply watermark to every page
% ----- change 'stamp' to 'nostamp'
%------ to omit watermark
%
\usepackage[nostamp]{draftwatermark}
% % Use the following to make modification
\SetWatermarkText{DRAFT}
\SetWatermarkLightness{0.95}

%% for the per mil symbol
\usepackage[nointegrals]{wasysym}

%% for copyright symbol
\usepackage{textcomp}

%% to allow to rotate pages to landscape
\usepackage{lscape}
%% to adjust table column width
\usepackage{tabularx}

% suppress bottom page numbers on first page of each chapter
% because they overlap with text
\usepackage{etoolbox}
\patchcmd{\chapter}{plain}{empty}{}{}

%% for more attractive tables
\usepackage{booktabs}
\usepackage{longtable}


\usepackage{graphicx}


% Double spacing, if you want it.
% \def\dsp{\def\baselinestretch{2.0}\large\normalsize}
% \dsp

% If the Grad. Division insists that the first paragraph of a section
% be indented (like the others), then include this line:
% \usepackage{indentfirst}

%%%%%%%%%%%%%%%%%%
% If you want to use "sections" to partition your thesis
% un-comment the following:
%
% \counterwithout{section}{chapter}
% \setsecnumdepth{subsubsection}
% \def\sectionmark#1{\markboth{#1}{#1}}
% \def\subsectionmark#1{\markboth{#1}{#1}}
% \renewcommand{\thesection}{\arabic{section}}
% \renewcommand{\thesubsection}{\thesection.\arabic{subsection}}
% \makeatletter
% \let\l@subsection\l@section
% \let\l@section\l@chapter
% \makeatother
%
% \renewcommand{\thetable}{\arabic{table}}
% \renewcommand{\thefigure}{\arabic{figure}}
%
%%%%%%%%%%%%%%%%%%


%% Stuff from https://github.com/suchow/Dissertate

% The following line would print the thesis in a postscript font

% \usepackage{natbib}
% \def\bibpreamble{\protect\addcontentsline{toc}{chapter}{Bibliography}}

\setcounter{tocdepth}{1} % Print the chapter and sections to the toc
% controls depth of table of contents (toc): 0 = chapter, 1 = section, 2 = subsection

\usepackage{biblatex}

\prelimpages

%% from thesisdown
% To pass between YAML and LaTeX the dollar signs are added by CII
\Title{Emily's Thesis Title}
\Author{Emily Pollock}
\Year{2021?}
\Program{Biological Anthropology}
\Chair{Steven M. Goodreau}{Title of my chair}{Biological Anthropology}
\Signature{person 1}
\Signature{person 2}
\Signature{person 3}

% commands and environments needed by pandoc snippets
% extracted from the output of `pandoc -s`
%% Make R markdown code chunks work
\usepackage{array}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifxetex
  \usepackage{fontspec,xltxtra,xunicode}
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
\else
  \ifluatex
    \usepackage{fontspec}
    \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \else
    \usepackage[utf8]{inputenc}
  \fi
\fi
\usepackage{color}
\usepackage{fancyvrb}
\DefineShortVerb[commandchars=\\\{\}]{\|}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\newenvironment{Shaded}{}{}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{\textbf{{#1}}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.56,0.13,0.00}{{#1}}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.25,0.63,0.44}{{#1}}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.25,0.63,0.44}{{#1}}}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.25,0.63,0.44}{{#1}}}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.25,0.44,0.63}{{#1}}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.25,0.44,0.63}{{#1}}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.38,0.63,0.69}{\textit{{#1}}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{{#1}}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{1.00,0.00,0.00}{\textbf{{#1}}}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.02,0.16,0.49}{{#1}}}
\newcommand{\RegionMarkerTok}[1]{{#1}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{1.00,0.00,0.00}{\textbf{{#1}}}}
\newcommand{\NormalTok}[1]{{#1}}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{\textbf{{#1}}}}
\newcommand{\BuiltInTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{\textbf{{#1}}}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.00,0.44,0.13}{\textbf{{#1}}}}


\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex,
              colorlinks=true,
              linkcolor=blue]{hyperref}
\else
  \usepackage[unicode=true,
              colorlinks=true,
              linkcolor=blue]{hyperref}
\fi
\hypersetup{breaklinks=true, pdfborder={0 0 0}}
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\setcounter{secnumdepth}{2} %% controls section numbering, e.g. 1 or 1.2, or 1.2.3

\begin{document}
\copyrightpage

\titlepage

\setcounter{page}{-1}
\abstract{``Here is my abstract''}

\tableofcontents
\listoffigures
\listoftables

\acknowledgments{``My acknowledgments''}

\dedication{\begin{center}``My dedication''\end{center}}

\textpages


\chapter*{Introduction}\label{introduction}
\addcontentsline{toc}{chapter}{Introduction}

Anthropologists have long recognized the importance of social
connections and behavioral variation among humans and our nonhuman
primate relatives. Indeed, the ability for us to participate in distinct
but potentially interlocking complex social networks has fueled our
evolution as a species and made our uniquely elaborate life possible.
Network analysis has often been utilized as a way to visually and
quantitatively represent these ties in order to understand their effects
on those connected to each other, from kinship, social support and
social capital, to the diffusion of information and transmission of
disease. These latter networks are crucially important to our
understanding of how human biosocial variation influences our health,
where the oft-beneficial complex social networks we maintain and
navigate every day can also put us at risk of exposure to infection.

transition to STIs

In order to understand the complex patterns by which sexually
transmitted infections (STIs) are transmitted throughout populations, we
first need to understand the behavior of human relationships and how
these behaviors generate the dynamic sexual network across which these
types of infections can spread.

This work is guided by the theoretical framework of the human ecology of
infectious disease, the investigation of how human behavior, social
patterns, and built environments interact with the broader pathogen
environment to influence our health. Of particular interest is not just
aggregate behavior, but also how variation in individual behavior
influences social patterns and alters the landscape through which
diseases spread, particularly as this variation relates to biological
age. Syndemic theory will also be used as a guide to understand how
variation in behaviors and patterns act synergistically to increase
vulnerability and exacerbate existing health disparities of certain
population subgroups (Singer et al., 2006).

can I pull some stuff from my PAA abstract about age?
\begin{itemize}
\tightlist
\item
  transition to a history of the evolution of epidemic models (ie. from
  compartmental where everything is basically independent and
  exponential through to ERGMs where formation can be quite elaborate
  but we've never spent much time thinking about dissolution)
\end{itemize}
Mathematical models are quantitative representations of real-life
systems and the processes within these systems important to the outcome
of interest. This form of inquiry is particularly useful when classic
scientific experiments to understand disease spread or intervention
efficacy cannot be conducted for either practical or ethical reasons, or
when specific processes or parameter values in a system are unknown. In
these situations, we use mathematical modeling as an in-silico
laboratory to explore ideas and test hypotheses. Of course, the form and
complexity of these models are determined by a variety of factors
including the type of question that needs answering and the natural
history of the infection of interest, but many types of mathematical
models rely on similar underlying assumptions. Without diving too deep
into the history of epidemic modeling, here I give a brief overview of
the various model forms to highlight some key similarities and
differences.

Initial mathematical models for epidemics were deterministic and
compartmental in nature. They did not represent people individually,
rather they group them into homogenous compartments representing
specific states of interest, a portion of which transitioned between
compartments at each time step based on a rate. In the most basic
models, the compartments are usually ``susceptible'' and ``infected''
and the rate of transition from susceptible to infected depends on the
rate of contact between the groups and the size of the infected group
relative to the whole population. Additional complexity can be added by
adding more compartments or states, like breaking down the state of
susceptible and infected into demographic states like race or age
groups, adding compartments for vector populations like mosquitoes, or
by representing a more complex natural history of the pathogen by
including states for groups such as ``exposed but not infectious'',
``recovered'', ``infected and symptomatic'', or ``infected and
asymptomatic'' to name a few. These models were deterministic in nature
because the transitions between compartments rely on unchanging rates:
the same proportion of each component transitions at each time point and
if you run a deterministic compartmental model (DCM) multiple times you
will alway have the same result.

Stochastic models grew out of this original framework as a way to
capture variability and uncertainty in the systems we wish to study. In
this scenario, some or all transitions between states were based on a
\emph{probability} of transitioning rather than a set rate, meaning that
not the same proportion of a state transitioned at every time step, but
on \emph{average}

Notice the assumptions implicit in the way transitions occur in these
models - it is memoryless, generating an exponential distribution (or
geometric if using discrete time).
\begin{itemize}
\item
  dynamic networks require information about relationship duration
\item
  why doing a bit better on dissolution/duration, especially by age,
  will be extra important for thinking about certain interventions for
  certain relatively short-lived infections (e.g.~partner services in
  chlamydia).
\item
  additionally, while births and deaths have been a part of models, only
  recently are we adding explicit age-dependent formation terms -- and
  age changes over the simulation -- what is this effect?\\
\item
  including age in dynamic models may sound straightforward but as we're
  going to see adds a surprising amount of complexity
\end{itemize}
exponential -- memoryless survival function, exchangeability

\chapter{Survival Analysis of Relationship Duration}\label{surv}
\begin{itemize}
\tightlist
\item
  main goal here to understand where in the distribution we may not be
  capturing when we use models based on a memoryless process, and
  explore some ways to do better within the constraints of feasibility
  imposed by epidemic models
\item
  so we primarily use the exponential distribution in the SA analyses
\item
  discuss survey data and censoring / truncation issues
\item
  And then flesh out the details of the analyses with a clear narrative
  and you have the core of a chapter!
\end{itemize}
The duration of sexual relationships across a population generates the
network structure largely responsible for either exposing individuals to
or protecting individuals from sexually transmitted infections (STIs).
In addition to dictating this period of possible exposure, relationship
durations relative to the pathogen-specific duration of infection are an
important driver of how quickly STIs can spread throughout a population.
Transmission beyond a pair of actors for infections with short durations
relative to relationship lengths is challenging and slow, and it is more
likely that an infection will be detected and treated or resolved
naturally prior to the dissolution of the relationship. If the duration
of infection and duration of relationships are more equal, there is a
greater chance that the infection can spread to future partners and
throughout the network. When partnerships overlap, transmission pathways
increase even among those individuals with few lifetime partners, and
this effect is even greater when the duration of overlap is large
(Armbruster, Wang, and Morris 2017; Morris and Kretzschmar 1997).

The pattern of relationship durations across the life-course is also
important because STIs often have distinct age patterns in terms of
prevalence. Individual age is often used as a predictor for risky sexual
behavior, but there is additional complexity when considering the effect
of age on the duration of relationships across the life-course. Young
age likely influences the immediate intentions for relationships
(i.e.~serious or casual), and the frequency at which individuals form
new relationships, but somewhat paradoxically it is also true that the
only people who can report extremely long relationships are those who
started them at young ages. This also introduces complex sampling issues
because most data on relationship durations is collected
cross-sectionally or retrospectively -- not longitudinally. Given the
importance of relationship duration to features of STI epidemiology
discussed above, there is growing interest in improving the
representation of relational durations in dynamic network models used to
study epidemics. This study demonstrates the ways in which the current
literature fails to represent this distribution and proposes a new
modeling framework to better capture these relationships across the
life-course.

One common class of models used to understand network influences on
patterns of STI transmission is known as separable temporal
exponential-family random graph models (STERGMs). These models are
governed by two expressions: one that represents the set of processes
that influence the formation of relationships, and a comparable one for
dissolution (Krivitsky and Handcock 2014). The current standard practice
for the dissolution models in this modeling framework assumes that once
a relationship begins, its persistence is governed by a constant hazard.
This memoryless process is a convenient simplifying assumption, adopted
because most hypotheses being explored relate to processes impacting
network formation or cross-sectional structure. However, it is unlikely
that this assumption faithfully represents the distribution all
relationship durations we observe across a wide range of ages.

Several recent models have begun to address this issue by splitting out
relationships into two categories: the first, marriages and
cohabitations or main partnerships, and the second, persistent or casual
partnerships. These are then modeled as separate networks
simultaneously. By structuring the model in this fashion, each network
has a hazard of dissolution specific to its type. (These models often
have a third network for one-time sexual contacts which last only one
time-step, but this network is not the focus of our study). While these
models are indeed able to reproduce the mean relationship lengths drawn
from empirical data, it remains unknown how well these strategies
reproduce the full distribution of lengths observed. In particular, the
memoryless assumption means that the modal length of main partnerships
remains near zero across all ages, which basic intuition says is not
true and descriptive data analysis confirms. Other work has considered
disaggregating relational durations by a single demographic attribute of
their members related to a hypothesis or prevention modality being
explored, but again with no further effort to capture the full
distribution, particularly by age (Goodreau et al. 2017; Jenness et al.
2017).

In this ongoing study, we seek to understand the changing distribution
of relationship duration over the life-course using data from the
National Survey of Family Growth, to evaluate which features the above
dissolution assumptions are capable of replicating and which they
cannot. We then introduce an alternative framework designed to more
faithfully represent these data and the different demographic and
data-collection processes that impact them in an age-structured
population over time. We use tools from both event history analysis and
network analysis to answer the following questions: First, under what
circumstances, if any, can an exponentially distributed time-to-event
model reasonably approximate empirical relationship duration data?
Second, does it make sense to lump marriages and cohabitations into one
network with the same dissolution probability? And third, can we better
capture the age-wise relationship distribution by using one network
where (1) relationships can transition between states (e.g.~from a
cohabitation into a marriage) rather than modeling several types
separately, and (2) where relational formation probabilities depend on
current relational status.

\textbf{Data}\\
The empirical data used in this study are drawn from the 2006-2010 and
2011-2015 waves of the National Survey of Family Growth (NSFG). The NSFG
surveys men and women aged 15-44 on many aspects of family life,
including but not limited to marriage and divorce, pregnancy,
contraception use, infertility, and other aspects of sexual and
reproductive behavior. In addition to the demographic information
recorded for each respondent and their sampling weights, in this study
we use the data collected in section C of the public use files on each
respondent's recent sexual partnerships with opposite-sex partners in
the last year, with a maximum of three partnerships reported. These data
include the century-month of first sexual contact, the century-month of
last sexual contact, whether the respondent considers this sexual
partnership to be ongoing, and the partnership status (marriage,
cohabitation, or other). We limit the combined data set to those
respondents who report at least one partnership in the last year. Out of
the original 43,303 respondents, our subset contains 32,516 respondents
who report on 40,443 sexual partnerships. Due to the study design, all
relationships that respondents report as ongoing on the day of interview
have right-censored relationship lengths, and there is left-truncation
present due to the large number or relationships that started prior to
the observation window but continued into it.

\textbf{Methods}\\
First the empirical relational duration data (using the start and end
dates of all reported relationships in NSFG) will be investigated using
histograms (overall and stratified by age category). Then, due to the
issues of right censoring and left truncation as a result of survey
design in NSFG, a reference survival curve will be constructed from the
empirical data using a Modified Kaplan-Meier model following (Burington
et al. 2010) and using the R package `survival'. Next, exploratory
parametric models will be estimated from the data (with corrections for
right-censoring and left-truncation) using a variety of distributions
(namely and latent mixture components) to gain intuition about the
underlying generative processes. Initial models will be covariate-free
(representing the effects of relationship duration only on the chances
of survival) and additional models will begin to examine the influence
of age on relationship duration, including (but not limited to) the
ego's age category, the reported current age difference between ego and
alter, and the ego's age category at the beginning of each reported
relationship. All models without latent components will be fit using the
R package `flexsurv' and the likelihood functions for all models with
latent components will be personally developed and models will be fit
using the maxLik package (Jackson 2016; Henningsen and Toomet 2011).

From PAA abstract: In our preliminary work, we first checked the
assumption that relationship duration can be modeled by a simple
memoryless process, and then explored some natural extensions to this
framework. In order to generate the reference distribution, we fit a
Kaplan-Meier model using a modified estimator to account for both
right-censoring and left-truncation following Burington et al (2010). We
then fit several parametric models (all adjusted for the above sampling
issues): first a simple exponential model to represent the memoryless
process assumption, then a Weibull distribution and Gamma distribution,
all with and without additional covariate attributes. Model fit was
evaluated primarily using the Akaike Information Criterion (AIC) and
visuals to understand which relationship lengths were represented better
than others, given our ultimate goal of adapting these into dynamic
network simulations. Below is a selection of explored models; parametric
models with covariate categories are displayed in color, with their
Kaplan-Meier reference curves plotted in black. All parameters in these
fitted models are statistically significant (p \textless{} 0.001).

\textbf{Initial Histograms}
\begin{figure}

{\centering \includegraphics[width=0.7\linewidth]{thesis_files/figure-latex/hists-1} 

}

\caption{All Relationships either Current or Ended in the Last Year}\label{fig:hists}
\end{figure}
\begin{figure}

{\centering \includegraphics[width=0.7\linewidth]{thesis_files/figure-latex/hist-agecat-1} 

}

\caption{All Relationships either Current or Ended in the Last Year, by Age Category}\label{fig:hist-agecat}
\end{figure}
\textbf{Results}

The first takeaway is that an exponential distribution alone is not
sufficient to capture the relationship distribution -- it overestimates
the survival of short relationships and underestimates the survival of
long relationships (top left figure, below). The Weibull and Gamma
perform better and capture more of the short relationships, suggesting
that there is important heterogeneity in the data, but like the first
models they also fail to capture the longest relationships. The age
category of the reporting individual is not explanatory across all age
categories (top right). This is perhaps not surprising, in that the age
distribution of relationship lengths is at least partly an emergent
property rather than a causal one. That is, no individual can have a
relationship that has lasted longer than they have been sexually active,
so the range of relationship lengths for young age categories is
relatively small. Meanwhile, the older age categories are challenging to
represent because the possible range of relationships is so much larger,
and are likely influenced not only by dissolution probabilities but also
by the changing formation probabilities over the lifecourse -- that is,
older people in long-term relationships do not start new relationships
at the same rate as others, and thus have relatively few relationships
that are short.

\includegraphics{thesis_files/figure-latex/exp-dist-surv-1.pdf}

The next two models test how appropriate it is to group relationships
defined as marriages and cohabitations into the same dissolution model,
as has been done in recent STERGMs. We see clear evidence that marriages
and cohabitations have distinct hazards of dissolution and the combined
marriage and cohabitation curve, like the simple exponential for all
relationships, dramatically fails to capture both the shortest and
longest relationships of these types (bottom right and bottom left
figures, respectively. These results are similar to other work in family
demography that has shown significant differences in the risk of
dissolution between cohabitations and marriages due to variation in
joint lifestyles (van Houdt and Poortman 2018). These results suggest to
us that previously developed STERGM dissolution models that only capture
the mean relationship length are not appropriate approximations of the
data, and that cohabitation represents a distinctly separate type of
relationship from marriages and other casual relationships and should be
treated as such in our networks.
\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s <-}\StringTok{ }\KeywordTok{summary}\NormalTok{(e.agecat)}
\KeywordTok{plot}\NormalTok{(km_agecat_weighted, }\DataTypeTok{lty=}\DecValTok{2}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{,}
     \DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{4}\OperatorTok{:}\DecValTok{9}\NormalTok{], }
     \DataTypeTok{ylab=}\StringTok{"S(t)"}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{"t, Weeks"}\NormalTok{, }
     \DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{348}\NormalTok{))}
\KeywordTok{lines}\NormalTok{(s}\OperatorTok{$}\StringTok{`}\DataTypeTok{e.agecat=15-19}\StringTok{`}\OperatorTok{$}\NormalTok{est, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{4}\NormalTok{], }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{)}
\KeywordTok{lines}\NormalTok{(s}\OperatorTok{$}\StringTok{`}\DataTypeTok{e.agecat=20-24}\StringTok{`}\OperatorTok{$}\NormalTok{est, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{5}\NormalTok{], }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{)}
\KeywordTok{lines}\NormalTok{(s}\OperatorTok{$}\StringTok{`}\DataTypeTok{e.agecat=25-29}\StringTok{`}\OperatorTok{$}\NormalTok{est, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{6}\NormalTok{], }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{)}
\KeywordTok{lines}\NormalTok{(s}\OperatorTok{$}\StringTok{`}\DataTypeTok{e.agecat=30-34}\StringTok{`}\OperatorTok{$}\NormalTok{est, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{7}\NormalTok{], }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{)}
\KeywordTok{lines}\NormalTok{(s}\OperatorTok{$}\StringTok{`}\DataTypeTok{e.agecat=35-39}\StringTok{`}\OperatorTok{$}\NormalTok{est, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{8}\NormalTok{], }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{)}
\KeywordTok{lines}\NormalTok{(s}\OperatorTok{$}\StringTok{`}\DataTypeTok{e.agecat=40-44}\StringTok{`}\OperatorTok{$}\NormalTok{est, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{9}\NormalTok{], }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{)}
\KeywordTok{legend}\NormalTok{(}\StringTok{"topright"}\NormalTok{, }\DataTypeTok{lty=}\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{6}\NormalTok{), }\KeywordTok{rep}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{6}\NormalTok{)), }\DataTypeTok{lwd=}\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{12}\NormalTok{)), }
       \DataTypeTok{col=}\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{4}\OperatorTok{:}\DecValTok{9}\NormalTok{],}\DecValTok{2}\NormalTok{)), }
       \DataTypeTok{legend =} \KeywordTok{c}\NormalTok{(}\StringTok{"15-19"}\NormalTok{, }\StringTok{"20-24"}\NormalTok{, }\StringTok{"25-29"}\NormalTok{, }\StringTok{"30-34"}\NormalTok{, }\StringTok{"35-39"}\NormalTok{, }\StringTok{"40-44"}\NormalTok{,}
                   \StringTok{"K-M Reference: 15-19"}\NormalTok{,}
                   \StringTok{"K-M Reference: 20-24"}\NormalTok{,}
                   \StringTok{"K-M Reference: 25-29"}\NormalTok{,}
                   \StringTok{"K-M Reference: 30-34"}\NormalTok{,}
                   \StringTok{"K-M Reference: 35-39"}\NormalTok{,}
                   \StringTok{"K-M Reference: 40-44"}\NormalTok{), }\DataTypeTok{bty=}\StringTok{"n"}\NormalTok{, }\DataTypeTok{cex=}\FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}
\begin{figure}

{\centering \includegraphics{thesis_files/figure-latex/unnamed-chunk-1-1} 

}

\caption{Kaplan-Meier vs. Constant Hazard by Current Age Category}\label{fig:unnamed-chunk-1}
\end{figure}
\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{s <-}\StringTok{ }\KeywordTok{summary}\NormalTok{(e.agecat)}
\KeywordTok{plot}\NormalTok{(km_agecat_weighted, }\DataTypeTok{lty=}\DecValTok{2}\NormalTok{, }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{,}
     \DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{4}\OperatorTok{:}\DecValTok{9}\NormalTok{], }
     \DataTypeTok{ylab=}\StringTok{"S(t)"}\NormalTok{, }\DataTypeTok{xlab =} \StringTok{"t, Weeks"}\NormalTok{, }
     \DataTypeTok{xlim=}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{348}\NormalTok{))}
\KeywordTok{lines}\NormalTok{(s}\OperatorTok{$}\StringTok{`}\DataTypeTok{e.agecat=15-19}\StringTok{`}\OperatorTok{$}\NormalTok{est, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{4}\NormalTok{], }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{)}
\KeywordTok{lines}\NormalTok{(s}\OperatorTok{$}\StringTok{`}\DataTypeTok{e.agecat=20-24}\StringTok{`}\OperatorTok{$}\NormalTok{est, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{5}\NormalTok{], }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{)}
\KeywordTok{lines}\NormalTok{(s}\OperatorTok{$}\StringTok{`}\DataTypeTok{e.agecat=25-29}\StringTok{`}\OperatorTok{$}\NormalTok{est, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{6}\NormalTok{], }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{)}
\KeywordTok{lines}\NormalTok{(s}\OperatorTok{$}\StringTok{`}\DataTypeTok{e.agecat=30-34}\StringTok{`}\OperatorTok{$}\NormalTok{est, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{7}\NormalTok{], }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{)}
\KeywordTok{lines}\NormalTok{(s}\OperatorTok{$}\StringTok{`}\DataTypeTok{e.agecat=35-39}\StringTok{`}\OperatorTok{$}\NormalTok{est, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{8}\NormalTok{], }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{)}
\KeywordTok{lines}\NormalTok{(s}\OperatorTok{$}\StringTok{`}\DataTypeTok{e.agecat=40-44}\StringTok{`}\OperatorTok{$}\NormalTok{est, }\DataTypeTok{type =} \StringTok{"l"}\NormalTok{, }\DataTypeTok{col =} \KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{9}\NormalTok{], }\DataTypeTok{lwd=}\DecValTok{4}\NormalTok{)}
\KeywordTok{legend}\NormalTok{(}\StringTok{"topright"}\NormalTok{, }\DataTypeTok{lty=}\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{6}\NormalTok{), }\KeywordTok{rep}\NormalTok{(}\DecValTok{2}\NormalTok{,}\DecValTok{6}\NormalTok{)), }\DataTypeTok{lwd=}\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\DecValTok{3}\NormalTok{,}\DecValTok{12}\NormalTok{)), }
       \DataTypeTok{col=}\KeywordTok{c}\NormalTok{(}\KeywordTok{rep}\NormalTok{(}\KeywordTok{brewer.pal}\NormalTok{(}\DecValTok{9}\NormalTok{, }\StringTok{"Blues"}\NormalTok{)[}\DecValTok{4}\OperatorTok{:}\DecValTok{9}\NormalTok{],}\DecValTok{2}\NormalTok{)), }
       \DataTypeTok{legend =} \KeywordTok{c}\NormalTok{(}\StringTok{"15-19"}\NormalTok{, }\StringTok{"20-24"}\NormalTok{, }\StringTok{"25-29"}\NormalTok{, }\StringTok{"30-34"}\NormalTok{, }\StringTok{"35-39"}\NormalTok{, }\StringTok{"40-44"}\NormalTok{,}
                   \StringTok{"K-M Reference: 15-19"}\NormalTok{,}
                   \StringTok{"K-M Reference: 20-24"}\NormalTok{,}
                   \StringTok{"K-M Reference: 25-29"}\NormalTok{,}
                   \StringTok{"K-M Reference: 30-34"}\NormalTok{,}
                   \StringTok{"K-M Reference: 35-39"}\NormalTok{,}
                   \StringTok{"K-M Reference: 40-44"}\NormalTok{), }\DataTypeTok{bty=}\StringTok{"n"}\NormalTok{, }\DataTypeTok{cex=}\FloatTok{0.8}\NormalTok{)}
\end{Highlighting}
\end{Shaded}
\begin{figure}

{\centering \includegraphics{thesis_files/figure-latex/unnamed-chunk-2-1} 

}

\caption{Kaplan-Meier vs. Constant Hazard by Current Age Category}\label{fig:unnamed-chunk-2}
\end{figure}
\chapter{Demography and Dynamic Network Simulations}\label{nets}

needs better title

Having gained insights about factors important (and not important) to
the patterns of relationship length over the age course from survival
analysis, the next steps initially seemed straightforward. First, I was
going to build a two-network simulation model comparable to recently
published models (where the casual/shorter relationships are represented
on one network and marriages and cohabitations are represented on
another) and analyze the patterns of relationship duration across the
simulated age range to understand the ways in which we are able to
recreate the empirical distribution and the ways in which we are not.
Second, I was going to build a network model with a new structure:
instead of modeling relationships on separate networks, I would begin
all relationships as casual relationships and have them transition over
time into cohabitations and marriages. Relationship dissolution
probability, as in the first model, would be based on relationship type.
By transitioning relationships over time -- a process much closer to
reality - instead of classifying certain relationships as, say,
marriages, at their onset, I hoped to match certain features of the
empirical distribution better. In particular: the increasingly uniform
distribution of relationship lengths at older ages as some individuals
maintain long-lasting marriages and others maintain cohabitations or
begin entirely new relationships.

Suffice it to say that I did not get to step two.

In mathematical models, the choice of model terms depends on the
question of interest and the underlying patterns in the data and this is
no less true for network models of sexual partnerships developed to
understand disease transmission. Several previously published models
using ERGMs and EpiModel to simulate epidemics focused on men who have
sex with men (MSM) populations in a narrow age range, 18-35 (\emph{cite
papers and also double check that this is true}). These models focused
on terms related to mixing patterns between races, the propensity to
form relationships with individuals relatively close in age, and the
likelihood of concurrent partnerships. Because prevalence of both main
and casual relationships remained relatively stable over the small age
range, the models did not include terms that used age as a predictor of
relationship formation. However, in this project, we focus on
heterosexual relationships over a larger age range (15-45). Unlike MSM,
there are large clear differences in the prevalence of main and casual
partnerships over this age range (\ref{fig:egodata-prep}), so we will
need to include terms that include age in our model. In addition to
influencing the distribution of relationship duration, these differences
are likely to be especially important if we want to use this type of
model to understand the processes that generate the large observed
differences in bacterial STI prevalence by age - originally one of the
broader goals of this dissertation.
\begin{figure}

{\centering \includegraphics[width=0.6\linewidth]{thesis_files/figure-latex/egodata-prep-1} 

}

\caption{Mean Degree by Ego Age and Relationship Type.}\label{fig:egodata-prep}
\end{figure}
As it turns out, adding age-related formation terms and other important
demographic processes to a dynamic network simulation has some
unexpected consequences.

\section{Base Model Overview \& STERGM
fit}\label{base-model-overview-stergm-fit}

several general trends in relationship formation (finish write-up and
cite) --
\begin{itemize}
\tightlist
\item
  individuals often select partners that are not their exact age
\item
  this difference in partner ages often increases over the life course
  (i.e.~adults usually have wider age differences between their partners
  than do adolescents)
\item
  it is common for men to partner with younger women (although the sex
  differences in relationship formation are not explored in this model,
  it's important to note that in a more realistic model the effect of
  aging out would disproportionately affect the women whose partners age
  out before them
\end{itemize}
(include model terms and coefs and explain terms) (full description of
EpiModelHIV module flow w/ parameters in appendix, brief overview here)

Cross network terms - we're going to avoid them due to complications

\section{Overview of Demographic Processes of
Interest}\label{overview-of-demographic-processes-of-interest}

The simulations run using the EpiModel API are distinct from the above
dynamic diagnostic in that in addition to tie formation and dissolution
at every time step, a series of modules is run that govern important
demographic processes: node departure, node entry, aging, and sexual
debut. Nodes automatically depart the model at age 45. This boundary was
determined by two things: 1) According to the CDC in their 2018
surveillance report, 97.4\% of all chlamydia infections were diagnoses
in the 15-44 age range (cite surveillance report) and 2) the National
Survey of Family Growth, the empirical data from which we estimate our
model, only surveys adults aged 15-44. There are likely other sources of
information that we could use to increase the age range, but it did not
seem necessary to our questions of interest. Note that implicit in this
decision is the elimination of all reported relationships among egos
aged 15-45 whose \emph{partners} are outside of this age range. The
degree distribution that we actually use to estimate the model (and are
trying to maintain during simulation) looks rather different than the
original distribution shown above, particularly in the
marriage/cohabitation network (see \ref{fig:egodata-2}. We will consider
the consequences of effect a later section.
\begin{figure}

{\centering \includegraphics[width=0.6\linewidth]{thesis_files/figure-latex/egodata-2-1} 

}

\caption{Mean Degree by Ego Age and Relationship Type, Restricted and Unrestricted Alters}\label{fig:egodata-2}
\end{figure}
In addition to the age boundary at 45, all individuals experience the
possibility of dying at each time step. Each node belongs to a class
based on their 5-year-age-category and their sex, and is evaluated for
death at every time step with the probability determined by data from
published in U.S. Vital Statistics documents (cite). Given that our age
range is relatively young, departures due to background mortality are
uncommon relative to the effect of the age boundary on which nodes
depart the model. Nodes enter at age 15 at a rate based on the expected
number of departures per time step in order to keep the population size
relatively stable. Like ASMR, the actual number of entires per time step
is stochastic but maintains a population size within 1-2\% of the
starting size of 50,000 nodes. Each time step in the simulation
represents one week, so nodes age by 1/52 per time step. Nodes enter the
population at age 15 and are evaluated for sexual debut at each time
step, with probability that increases until age 29 to match the
age-at-debut distribution as reported in the NSFG. In accordance with
the data, some individuals will never debut into the heterosexual
population and will therefore never form a tie in these networks.

\section{Diagnostic Results}\label{diagnostic-results}

(to demonstrate closed-system effectiveness without demography, fixed
nodal attributes)\\
The final step in evaluate the performance of an estimated STERGM prior
to the simulation is to run a dynamic diagnostic. In this diagnostic, we
simulate the STERGM for X repetitions of Y time steps and evaluate the
network statistics over time. At each time step, ties can form and ties
can dissolve based on the model coefficients. If the model is estimated
properly and sufficient MCMC intervals are used, the network formation
statistics should hover around their estimated targets. In this
diagnostic we also evaluate the duration of ties and the rate of tie
dissolution to ensure the dissolution targets are met. It is important
to note that this diagnostic is an indicator of model performance in a
closed system: all nodal attributes are fixed, no nodes exit, and no new
nodes enter the population.
\begin{figure}

{\centering \includegraphics[width=0.6\linewidth]{thesis_files/figure-latex/diagnostic-results-1} 

}

\caption{Comparison: Egodata vs Diagnostic Mean Degree.}\label{fig:diagnostic-results}
\end{figure}
\begin{figure}

{\centering \includegraphics[width=0.6\linewidth]{thesis_files/figure-latex/dynamic-duration-m-1} 

}

\caption{Mean Relationship Lengths in Diagnostic}\label{fig:dynamic-duration-m}
\end{figure}
takeaways:\\
- reproduces mean deg dist\\
- meets duration targets after time for burn in

\section{Simulation Results}\label{simulation-results}

Unlike the dynamic diagnostics, when we run these simulations with
demographic processes, several metrics stray from their target values.
First, the mean degree, or average number of relationships per person,
is too low in both the marriage/cohabitaiton network and in the casual
network (by roughly five and four percent respectively). Second, the
mean relationship length is 24\% too short in the marriage network but
8\% too long in the casual network. Finally, the distribution of
relationships across both networks is not as expected based on the
empirical data. In the marriage network, there are far too few
relationships among egos aged 18-31, and too many relationships in the
older egos. The casual network displays a similar effect through a
narrower age range. Here, the 15-22 year olds have too few
relationships, the 23-34 year olds have slightly too many, and the
oldest members are roughly the correct amount.
\begin{table}

\caption{\label{tab:scen1-tab}Mean Degree Comparison, Targets and Base Simulation}
\centering
\begin{tabular}[t]{rrr}
\toprule
Target & Base & Pct Off\\
\midrule
0.455 & 0.432 & -0.0505495\\
0.159 & 0.154 & -0.0314465\\
\bottomrule
\end{tabular}
\end{table}
\begin{table}

\caption{\label{tab:scen1-duration}Expected and Simulation Mean Relationship Length, Weeks}
\centering
\begin{tabular}[t]{lrrr}
\toprule
  & Target & Simulation & Pct Off\\
\midrule
Marriage/Cohab & 476 & 361 & -24.16\\
Casual & 95 & 102 & 7.37\\
\bottomrule
\end{tabular}
\end{table}
\begin{figure}

{\centering \includegraphics{thesis_files/figure-latex/scen1-networks-1} 

}

\caption{Base Simulation: Mean Degree by Age.}\label{fig:scen1-networks}
\end{figure}
Because we observed that in the marriage/cohabitation network there is
an overrepresentation of relationships among the older egos, and the
model coefficients suggests that older nodes are in general more likely
to form relationships than younger nodes (with some tapering as age
increases), we theorized that when a node aged 45 aged out and broke the
tie with their partner (who is likely to be somewhat close in age), that
the partner remaining in the simulation very quickly forms a new
relationship. However, the tie that dissolved as a result of one partner
leaving the simulation due to this age boundary is not a true
dissolution, and these newly formed relationships should not actually
exist because the remaining partner should not actually be eligible to
form a new relationship in the network yet. Perhaps then, these new,
short relationships in older ages contribute both to the lower than
expected mean relationship duration in the marriage network and the
lower than expected mean degree at younger ages.

\section{Considering the effect of older
partners}\label{considering-the-effect-of-older-partners}

We consider two ways to address the effect of partners outside the age
boundary. First, we prevent egos whose partners have aged out from
immediately forming new relationships by adding an offset terms for egos
who meet this condition. In this scenario we hope that by preventing new
relationships from forming among egos whose previous relationships were
terminated artifically by the age boundary, the simulation will better
match the data with the restricted alter set and increase the mean
relationship length by generating new relationships at earlier ages. In
the second scenario, we increase the age at which egos depart the
simulation to age 65. While we may not be interested in modeling
individuals older than 45 for epidemiological reasons, it may be
worthwhile to keep them in the simulation over a longer period of time
to avoid the artificial ending of relationships. In this case we hope to
match the empirical mean degree distribution among egos with the
age-unrestricted alter set. However, because we would be simulating
individuals outside the age range in the data we used for estimation, we
may run into additional issues.

\subsection{Offset for partner
age-out}\label{offset-for-partner-age-out}

This scenario adds an offset term to the formation model
(``olderpartner'') for egos whose alters are outside of the 15-45 age
range modeled in the simulation. During estimation there are already
some egos whose partners are outside the age range so they appear to
have degree 0 and do not contributed to the expected edge count but are
flagged as ``olderpartner=1''. During the simulation, if an individual
ages out while they are in a relationship, the remaining partner gets
flagged by the ``olderpartner'' attribute and are prohibited from
forming a new relationship. The probability of becoming available for a
relationship on any future time step is equal to 1/expected duration of
the relationship type, although in the case of the marriage/cohab
network relationships last so long that it's unlikely that a node become
available for the rest of their simulation lifecourse (unless the age
difference between partners was exceptionally large, which is not
impossible).

I don't necessarily expect this to solve the issue of the overall mean
degree, but if we prevent relationships that only exist due to the age
boundary, perhaps these relationships will be distributed among the
younger issues. In turn these relationships would begin earlier, and
possibly increase the average mean duration.

\emph{Results}

The first thing we note is that this offset did not largely influence
the overall mean degree in either network, nor did it increase the mean
relationship duration in the marriage/cohabitation network (mean
relationship length was also unchanged in the casual network, but we did
not necessarily expect it to). However, when comparing mean degree by
age between scenarios, the offset did correct much of the
overrepresentation of relationships at the older ages, and also slightly
increased the mean degree in the youngers (these changes are subtle but
present). The casual network was largely uninfluenced by this offset,
but that would be expected given that older ages are actually less
likely to form casual partnerships than younger ages.
\begin{table}

\caption{\label{tab:scen2-tab}Mean Degree Comparison, Older Partner Offset}
\centering
\begin{tabular}[t]{rrr}
\toprule
Target Mean Degree & Sim Mean Degree & Pct Off\\
\midrule
0.455 & 0.434 & -0.0461538\\
0.159 & 0.154 & -0.0314465\\
\bottomrule
\end{tabular}
\end{table}
\begin{table}

\caption{\label{tab:scen2-duration}Relationship Duration: Older Partner Offset, Weeks}
\centering
\begin{tabular}[t]{lrrr}
\toprule
  & Target & Simulation & Pct Off\\
\midrule
Marriage/Cohab & 476 & 361 & -24.16\\
Casual & 95 & 102 & 7.37\\
\bottomrule
\end{tabular}
\end{table}
\begin{figure}

{\centering \includegraphics[width=0.8\linewidth]{thesis_files/figure-latex/scen2-networks-1} 

}

\caption{Mean Degree Comparison: Base vs Offset.}\label{fig:scen2-networks}
\end{figure}
\subsection{Increase age boundary}\label{increase-age-boundary}

In this scenario, we hope to move the degree distribution closer to the
egodata distribution with the age-unrestricted alters (blue dots) -- the
distribution that better represents reality. This scenario includes the
offset for ``older partners'' but employs it in a slightly different
fashion. In the previous scenario, edges dissolved artificially when one
of the partners left the model at age 45. We now allow those
relationships to continue as they would normally by increasing the age
of departure in the model to age 65. However, we use the offset to
prevent any nodes older than 45 but not in a relationship from forming
new relationships. Only relationships that began prior both partners
turning 45 exist.

\emph{Results}

First off, it is clear that we can easily recover the marriage and
cohabitations lost to the age boundary among egos in the 35-45 age range
simply by keeping their older partners in the model, even if the data
used to estimate the model did not include these partners. However, this
approach has consequences. Because the model is targeting a mean degree
based on the restricted partner data, the maintenence of relationships
among 35-45 year olds increased the overall mean degree beyond the
target and also comes at the expense of relationships among the younger
ages, the section of the distribution that we already fail to match
well. The mean age of relationships has increased, but this is clearly a
result of the relationship at older ages, thus only a partial success.
The casual network also displays some undesireable qualities similar to
the cohab network. The mean degree is too low at the expense of the
younger age group and the mean relationship length is unchanged.
\begin{table}

\caption{\label{tab:scen3-tab}Mean Degree Comparison, Increased Age Boundary}
\centering
\begin{tabular}[t]{rrr}
\toprule
Target Mean Degree & Sim Mean Degree & Pct Off\\
\midrule
0.455 & 0.459 & 0.0087912\\
0.159 & 0.143 & -0.1006289\\
\bottomrule
\end{tabular}
\end{table}
\begin{table}

\caption{\label{tab:scen3-duration}Relationship Duration: Increased Age Boundary, Weeks}
\centering
\begin{tabular}[t]{lrrr}
\toprule
  & Target & Simulation & Pct Off\\
\midrule
Marriage/Cohab & 476 & 413 & -13.24\\
Casual & 95 & 104 & 9.47\\
\bottomrule
\end{tabular}
\end{table}
\begin{figure}

{\centering \includegraphics{thesis_files/figure-latex/scen3-networks-1} 

}

\caption{Mean Degree Comparison: Increased Age Boundary.}\label{fig:scen3-networks}
\end{figure}
\emph{Discussion}

conclusion: we keep offset in all future scenarios but not older
partners, older partners may be a good idea in some case but we have to
rethink some things especially if the younger ages are going to perform
worse

\section{Relationship Length \& The Simulation
Window}\label{relationship-length-the-simulation-window}

So far, nothing we have done has largely influenced the issues with
relationship duration in these networks. In the marriage/cohab network,
the mean duration falls nearly 2 years short of the expected length and
in the casual network the mean duration is roughly 3 months too long.
There are a few possible reasons that there may be a mismatch between
the formation and dissolution coefficients in-simulation that may
contribute to these outcomes.
\begin{figure}

{\centering \includegraphics[width=0.6\linewidth]{thesis_files/figure-latex/plot-expdist-1} 

}

\caption{Predicted Distribution of Marriage/Cohab Relationship Lengths}\label{fig:plot-expdist}
\end{figure}
From our survival analysis it is clear that the exponential
distribution, even when separated into separate networks by relationship
type, had some serious limitations in its ability to represent the full
distribution of relationship lengths - both by age and across the whole
population. One of the limitations that may pertain to the right tail of
the distribution. An exponential distribution with a mean of roughly 476
weeks (the mean cross-sectional length in the empirical data) has a very
long right tail extending beyond a normal human lifespan, 104 years.
Clearly this tail isn't possible to observe, even less so when you
consider that the window of observation in the simulation is equal to
the age range of the population, 15-45 (30 years).
\ref{fig:plot-expdist} shows the density plot of relationships lengths
that are exponentially distributed with a mean of 476 weeks. While
96.37\% of observsations lay within the simulation window, the removal
of the tail lowers the mean observerable relationship length based on
this distribution (the mean of relationship lengths if you remove the
observations that are impossible to occur in the simulation) from 476
weeks to 415 weeks.

*need figure legend, vertical line is simulation window

In this scenario, we increase the edges formation coefficient by the
difference between the log odds of the target mean duration and the log
odds of the observable mean duration in the marriage network. (this may
be a good time to explain the edapprox?) (also show that the
``observable'' mean duration in the casual network is essentially the
same because the right tail truncation is so small it doesn't influence
the mean much.)
\begin{itemize}
\tightlist
\item
  only display marriage/cohab network here b/c casual remains unchanged
  (no cross-network terms)
\end{itemize}
\begin{table}

\caption{\label{tab:scen5-tab}Mean Degree Comparison: Edapprox Correction}
\centering
\begin{tabular}[t]{rrr}
\toprule
Target Mean Degree & Sim Mean Degree & Pct Off\\
\midrule
0.455 & 0.449 & -0.0131868\\
0.159 & 0.153 & -0.0377358\\
\bottomrule
\end{tabular}
\end{table}
\begin{table}

\caption{\label{tab:scen5-duration}Relationship Length: Edapprox Correction, Weeks}
\centering
\begin{tabular}[t]{lrrr}
\toprule
  & Target & Simulation & Pct Off\\
\midrule
Marriage/Cohab & 476 & 366 & -23.11\\
Casual & 95 & 102 & 7.37\\
\bottomrule
\end{tabular}
\end{table}
\begin{figure}

{\centering \includegraphics[width=0.6\linewidth]{thesis_files/figure-latex/scen5-marcoh-1} 

}

\caption{Mean Degree Comparison: Edapprox Correction, Marriage/Cohab.}\label{fig:scen5-marcoh}
\end{figure}
\section{Formation \& Departure}\label{formation-departure}

let's think about why we're seeing the things we are\\
* both networks have too few edges, particularly in early years\\
* both dissolution rates slightly too low\\
* marriage/cohab network: duration far too low\\
* casual network: duration too high\\
* tests:\\
* marriage/cohab -- adj formation for earlier edges and longer
durations\\
* edapprox for impossible length durations - this went in the right
direction but influential enough * add't corrections-- what does it take
to hit the correct mean deg? does that help duration?\\
* casual -- adj formation for earlier edges, but also departure for too
long relationships (gets back to departure correction and the likelihood
that a departure eliminates an edges in this network, which I don't
think I've explained yet)?

In this scenario, I consider the

We've seen that there are some small adjustments that we can make to the
model structure to better capture the mean degree at the youngest and
oldest ages, but there remains the problem that neither the
marriage/cohabitation network nor the casual network maintain the target
mean degree, nor do they hit the target mean relationship duration.
Issues relating to maintaining mean degree under various demographic
conditions are not unheard of, and some corrections have already been
implemented. For example, the issue of maintaining mean degree in a
growing population has been addressed by Kritvitsky, Handcock and Morris
(2011). Additionally, a departure correction exists to maintain mean
degree and relationship duration in the presence of node departure (cite
Steve's document). I will briefly review this departure correction as it
is currently implemented here and think through a possible extension.
Current Implementation: Departure Correction The node departure
correction used in the model estimation-to-simulation workflow was
developed after the observation that when nodes were removed from the
simulation to mimic, for example, background age-specific mortality, the
mean degree of the network became lower than expected, as does the mean
duration of relationships. The logic is relatively straightforward: the
statistical model underlying these network simulations balances the
probability of tie formation with the probability of tie dissolution in
order to maintain a target number of ties in the network. However, when
nodes depart, some additional ties will break due to this process,
lowering mean degree and the mean duration of ties. This node death is
exogenous to the originally estimated statistical model, and therefore
``unexpected''. To counter the lowering of relationship duration (and
subsequently mean degree) related this excess node death, the expected
(endogenous) duration of ties is increased such that the \emph{average}
duration is maintained.\\
The departure correction implemented in previous models has two
components: 1) the mortality rate per time step averaged across the
entire population, and 2) the rate at which individuals depart the
simulation due to the age boundary, calculated as 1/(time steps each
node is expected to be observed in the simluation). In the past this
approach has
\begin{table}

\caption{\label{tab:scen6-tab}Mean Degree Comparison: Edapprox Correction}
\centering
\begin{tabular}[t]{rrr}
\toprule
Target Mean Degree & Sim Mean Degree & Pct Off\\
\midrule
0.455 & 0.457 & 0.0043956\\
0.159 & 0.145 & -0.0880503\\
\bottomrule
\end{tabular}
\end{table}
\begin{table}

\caption{\label{tab:scen6-duration}Relationship Length: Edapprox Correction, Weeks}
\centering
\begin{tabular}[t]{lrrr}
\toprule
  & Target & Simulation & Pct Off\\
\midrule
Marriage/Cohab & 476 & 382 & -19.75\\
Casual & 95 & 95 & 0.00\\
\bottomrule
\end{tabular}
\end{table}
\begin{figure}

{\centering \includegraphics{thesis_files/figure-latex/scen6-networks-1} 

}

\caption{Mean Degree Comparison: Departure Corrections.}\label{fig:scen6-networks}
\end{figure}
\begin{table}

\caption{\label{tab:summary-table}Mean Degree Comparison Summary Table}
\centering
\begin{tabular}[t]{rrrrrr}
\toprule
Target & Base & Older Partner Offset & Increased Age Boundary & Sim Window Correction & Sim Window + Departure\\
\midrule
0.455 & 0.432 & 0.434 & 0.459 & 0.449 & 0.457\\
0.159 & 0.154 & 0.154 & 0.143 & 0.153 & 0.145\\
\bottomrule
\end{tabular}
\end{table}
\begin{table}

\caption{\label{tab:summary-durs}Mean Relationship Duration Comparison Summary Table}
\centering
\begin{tabular}[t]{lrrrrrr}
\toprule
  & Target & Base & Older Partner Offset & Increased Age Boundary & Sim Window Correction & Sim Window + Departure\\
\midrule
Marriage/Cohab & 476 & 361 & 361 & 413 & 366 & 382\\
Casual & 95 & 102 & 102 & 104 & 102 & 95\\
\bottomrule
\end{tabular}
\end{table}
\section{Sexual Debut}\label{sexual-debut}

Representing the sexual debut process is both complex and highly
important if we wish to model sexually transmitted diseases in
adolesents and young adults. In the U.S., more than 50\% of all sexually
transmitted bacterial infections such as chlamydia and gonorrhea
diagnosed yearly occur among individuals aged 15-24, but not everyone in
the age group are sexually active, which concentrates the transmissions
into subset of the population and increases the probability of exposure
to an STI for those sexually active moreso than at older ages. It is
important then, to approximate this process in simulation as faithfully
as possible. If too many individuals are able to form sexual
partnerships in the model, we risk under-estimating the risk of exposure
for those sexually active and conversely over-estimating the risk of
exposure if too few are sexually active.

Estimating and simulating the sexual debut process is complex for
several reasons. First, because our empirical data is cross-sectional,
the proportion of individuals at each age who have sexually debuted at
the time of their interview is not necessarily monotonic, but is mostly
monotonic for the formative debut years - until roughly 97\% of the
population has reported sex with an opposite-sex partner. In the
simulation we stop estimating debut after this threshold is reached
around age 29, meaning not every person will have an opposite-sex
partnership. This way we use the population composition of the NSFG but
do not have to beforehand decide which members of the population will
debut heterosexually. The second complicating factor is that the rate of
debut is clearly not consistent across ages 15-29. The proportion of
individuals who report having had at least one opposite-sex sexual
partner rapidly increases throughouht the late teen and early 20s, and
then slows. Bearing this in mind\ldots{}I then used this
data\ldots{}.fit the models\ldots{}different parameters by age
groups\ldots{}.representing weekly probability of debut.

insert debut table graph

The major caveat to this approach is that it does not mechanistically
represent the debut process as well as desired . In real life, a person
``debuts'' by entering into a sexual partnership. This puts the model in
a bit of a catch-22 situation: an individual can't debut in real life
until they form a sexual partnership, but in order to form a sexual
partnership in the model, they must already be ``debuted''. We can match
the distribution of sexually debuted individuals, but it is possible
that the number of individiduals who have ``debuted'' does not equal the
number of individuals who have actually formed a relationship at any
point in the simulation.

And indeed this is the case - talk about effective debut

What if instead we used the ``debut'' term to model the idea of ``sexual
eligibility'' rather than explictly debut? The concept is
straightforward: in most cases, an individual would decide that they are
\emph{ready} to begin having sex some period of time prior to actually
forming a sexual partnership (or transitioning a relationship from a
non-sexual partnership to a sexual one). It is perhaps this underlying
trait that we should model instead, allowing us to model the sexual
history of individuals in our model more completely. Unfortunately our
survey data don't allow us to answer this question directly (i.e.~at
what age did you decide you were ready for sex vs at what age did you
actually start having sex), and the literature has laregly focused more
on individual characteristics and within-partership dynamics that
predict sexual debut rather than quantifying the time to readiness or
the time from readiness to debut (cite that review paper, others).

However, it is possible that the mis-match between what the ``debuted''
term acts in our model and what it represents in real life contibutes to
why our mean degree among the younger population in both networks is too
low, so in this scenario we alter

now, in this model setup, the rate of sexual debut does not influence
the birth/arrival rate in the model - as mentioned above the model is
designed to have a relatively stable population with an arrival rate
based on the expected number of departures at each time step. Sexual
debut however does dictate whether an individual is allowed to form a
relationship, and the number of un-debut persons is jointly estimated in
the model, so deviations from the original distribution will influence
the likelihood of tie formation\ldots{}

\emph{Results}

The switch to an ``eligibility'' metric had some dramatic effects on the
casual network and to a lesser extend the marriage/cohabitation network.
In the marriage network, the overall mean degree has increased to only
about 1\% less than the target, and although we see increases in the
mean degree across almost all ages, the effect is larger in the younger
half of the population. However the added number of egos available to
form a marriage or cohabitation has not helped us enough to meet our
by-age targets in this subset. The increase in the number of
realtionships that begin at earlier ages has increased the mean
relationship length by about 2.5 months, but we still fall far short of
the target. In the casual network, the increase in available egos for
casual relationships has led to a large increase in the mean degree in
the younger ages. In fact, the distribution comes very close to the mean
degree targets though adolesence and the early 20s, but exceeds the
targets until roughly age 30. The overall increase in relationships
leads this network to also exceed the target mean degree by roughly
20\%.

but -- let's look at actual debut in-simulation neither approach fits
data

\emph{1-Year Eligibility}
\begin{table}

\caption{\label{tab:scen4-tab}Mean Degree Comparison: 1-Year Eligibility}
\centering
\begin{tabular}[t]{rrr}
\toprule
Target Mean Degree & Sim Mean Degree & Pct Off\\
\midrule
0.455 & 0.465 & 0.0219780\\
0.159 & 0.167 & 0.0503145\\
\bottomrule
\end{tabular}
\end{table}
\begin{table}

\caption{\label{tab:scen4-duration}Relationship Length, 1-Year Eligibility, Weeks}
\centering
\begin{tabular}[t]{lrrr}
\toprule
  & Target & Simulation & Pct Off\\
\midrule
Marriage/Cohab & 476 & 387 & -18.7\\
Casual & 95 & 95 & 0.0\\
\bottomrule
\end{tabular}
\end{table}
\begin{figure}

{\centering \includegraphics{thesis_files/figure-latex/scen4-networks-1} 

}

\caption{Mean Degree Comparison: Eligibility.}\label{fig:scen4-networks}
\end{figure}
\emph{Calibrated Eligibility}
\begin{table}

\caption{\label{tab:calib-elig-tab}Mean Degree Comparison, Calibrated Eligibility}
\centering
\begin{tabular}[t]{rrr}
\toprule
Target Mean Degree & Sim Mean Degree & Pct Off\\
\midrule
0.455 & 0.478 & 0.0505495\\
0.159 & 0.200 & 0.2578616\\
\bottomrule
\end{tabular}
\end{table}
\begin{table}

\caption{\label{tab:calib-elig-duration}Relationship Duration: Calibrated Eligibility, Weeks}
\centering
\begin{tabular}[t]{lrrr}
\toprule
  & Target & Simulation & Pct Off\\
\midrule
Marriage/Cohab & 476 & 397 & -16.6\\
Casual & 95 & 95 & 0.0\\
\bottomrule
\end{tabular}
\end{table}
\begin{figure}

{\centering \includegraphics{thesis_files/figure-latex/calib-elig-networks-1} 

}

\caption{Mean Degree Comparison: Calibrated Eligibility.}\label{fig:calib-elig-networks}
\end{figure}
\emph{Young Age Formation Boost}
\begin{table}

\caption{\label{tab:youngboost-tab}Mean Degree Comparison, Young Age Formation Boost}
\centering
\begin{tabular}[t]{rrr}
\toprule
Target Mean Degree & Sim Mean Degree & Pct Off\\
\midrule
0.455 & 0.513 & 0.1274725\\
0.159 & 0.184 & 0.1572327\\
\bottomrule
\end{tabular}
\end{table}
\begin{table}

\caption{\label{tab:youngboost-duration}Relationship Duration: Young Age Formation Boost, Weeks}
\centering
\begin{tabular}[t]{lrrr}
\toprule
  & Target & Simulation & Pct Off\\
\midrule
Marriage/Cohab & 476 & 419 & -11.97\\
Casual & 95 & 95 & 0.00\\
\bottomrule
\end{tabular}
\end{table}
\begin{figure}

{\centering \includegraphics{thesis_files/figure-latex/youngboost-networks-1} 

}

\caption{Mean Degree Comparison: Young Age Formation Boost.}\label{fig:youngboost-networks}
\end{figure}
\begin{figure}

{\centering \includegraphics[width=0.6\linewidth]{thesis_files/figure-latex/effective-debut-comparison-1} 

}

\caption{Percent Debuted In-Sim vs Data, Various Scenarios}\label{fig:effective-debut-comparison}
\end{figure}
\begin{table}

\caption{\label{tab:debut-summary-tab}Mean Degree Comparison Summary Table, Sexual Debut Corrections}
\centering
\begin{tabular}[t]{rrrrr}
\toprule
Target & Default Debut & 1-Year Elig & Calibrated Elig & Young Formation Boost\\
\midrule
0.455 & 0.457 & 0.465 & 0.478 & 0.513\\
0.159 & 0.145 & 0.167 & 0.200 & 0.184\\
\bottomrule
\end{tabular}
\end{table}
\begin{table}

\caption{\label{tab:debut-summary-dur}Mean Relationship Duration Summary Table, Sexual Debut Corrections}
\centering
\begin{tabular}[t]{lrrrrr}
\toprule
  & Target & Default Debut & 1-Year Elig & Calibrated Elig & Young Formation Boost\\
\midrule
Marriage/Cohab & 476 & 382 & 387 & 397 & 419\\
Casual & 95 & 95 & 95 & 95 & 95\\
\bottomrule
\end{tabular}
\end{table}
\subsection{\texorpdfstring{\emph{Discussion}}{Discussion}}\label{discussion}
\begin{itemize}
\item
  not a one-size-fits-all solution
\item
  still concerned about who in the population is sexually active and the
  under/overestimate of exposure risk
\item
  really hard to empirically estimate ``eligibility'' concept, probably
  so related to potential-sexual-partnership dyanmics it's hard to say
  if this correction was even close to truth
\item
  using and ``effective debut'' metric of who has ever had a relatinship
  over the course of the simulation reveals that neither approach hits
  target actual debut
\end{itemize}
but again related to estimation mis-match between estimation and
simulation

conclusion: continue to use debut not eligibility

\section{OTHER - age dist??}\label{other---age-dist}

should I have a section on the age distribution? it levels out to be
slightly different than the egodata, which likely has some influence but
is unlikely to be the reason for the massive gap in the younger age mean
degree dist

\section{future work}\label{future-work}
\begin{itemize}
\tightlist
\item
  cross-network terms - probably going to do most analysis on the
  independent networks but will show both and point at where there are
  holes (hey by the time this gets finished maybe Chad will have already
  figured this out)\\
\item
  need to think about race and sex differences in formation and
  absdiff(age) by sex if we want to use this for applied work
\end{itemize}
\chapter{Chlamydia, Acquired Immunity, \& Expedited Partner
Therapy?}\label{ept}

copying over some text from diss proposal:

C. trachomatis is an obligate intracellular bacterium transmitted
through sexual contact among humans. Chlamydial infections are most
often asymptomatic. Untreated infections in women are an additional
public health concern because they can lead to a variety of sequalae
including pelvic inflammatory disease, scarring of ovaries and fallopian
tubes, ectopic pregnancies, chronic pain, and infertility. Repeat
infections are common and are an additional risk factor for the
development of the above sequelae (Brunham and Rey-Ladino 2005). There
is a great deal of uncertainty regarding the natural history of
chlamydia, but the duration of infection for untreated individuals is
generally thought to be up to 6 months for men and a year or more for
women (Golden et al. 2000; Satterwhite et al. 2013). Chlamydia is
usually treated with azithromycin or doxycycline, and unlike other
common STIs like syphilis and gonorrhea, true antibiotic resistance is
rare (Kong et al. 2015).

Chlamydia is the most common reportable disease in the United States and
incidence, particularly adolescents and young adults aged 15-29, is
increasing nationwide. The Centers for Disease Control and Prevention
(CDC) estimates that half of all new STI infections (including
gonorrhea, syphilis, and others) occur in those aged 15-24 despite them
making up only a quarter of the sexually active population. Even in
places like King County, Washington, where overall rates have remained
stable, longstanding acknowledged disparities in prevalence by race are
marked and continue to increase (2015 SKCPH STD Report). These rates are
particularly distressing in light of the fertility consequences of
long-term infection and reinfection: it is estimated that in King
County, over 60\% of non-Hispanic Black women have had at least one
chlamydia infection by age 34 (a rate 5x higher than non-Hispanic White
women) and 1 in 500 of non-Hispanic Black women develops
chlamydia-associated tubal factor infertility over their life-course
(Chambers et al. 2018).

The United States has some of the highest STD rates in the
industrialized world, and despite this, funding for public health
programs dedicated to these issues has largely declined (CDC 2016 STD
Report). As a result, few health departments are able to offer
traditional partner notification services, where a patient who tests
positive for an STI gives the contact information of their recent sex
partners to the health department, and the department then contacts
their partners with the hope that these partners will then get tested
and, if necessary, treated. Expedited partner therapy (EPT) was
developed with this scenario in mind (See figure 2). Under EPT, a
patient who tests positive, upon receipt of their own treatment,
receives either additional antibiotic pills for their recent sexual
partners or prescriptions for treatment that their partners can fill.
The patient then is expected to hand-deliver either the treatment or
prescription to their partner(s), who take the medicine at their own
discretion and without the need for a positive lab test. By using these
actors to essentially leverage their sexual network in reverse, this
system hopes to decrease the time to treatment for all possible infected
partners and increase the total number of partners treated. It can also
reduce re-infection among the index patients if the partnerships are
ongoing. There have been several clinical trials of EPT across the US
(and Europe), including Washington State. These trails demonstrated that
relative to traditional referral practices, EPT provision increased the
proportion of partners who were ultimately treated, reduced the number
of individuals who were re-infected at follow-up, and was less costly if
at least 30\% of partners were treated via EPT (CITE). Despite these
results and a growing body of evidence in support, widespread
implementation of EPT has been slow and there are still many questions
to be answered.

also -- EPT as a tool for health equity, not just effective
population-level decrease in prevalence -- can be more effective in
high-prevalance groups?

Annals of Internal Medicine Article High Incidence of New Sexually
Transmitted Infections in the Year following a Sexually Transmitted
Infection: A Case for Rescreening - Peterman et al

Arrested Immunity Hypothesis One of the paradoxes in era of modern
public health is that chlamydia incidence has actually increased overall
in the presence of mass control programs. In Sweden, Norway, Finland and
Canada the rates initially decreased but then resumed increasing, and in
Australia, United States, and the United Kingdom the rates never stopped
increasing even after program initiation, although this second pattern
has been attributed to the challenges of implementing control programs
consistently throughout a large population (Brunham and Rekart 2008).
These areas now experience incidence rates higher than rates prior to
introduction of control programs. Additionally, a regression analysis
using data from family planning clinics in Region X of the United States
(Alaska, Washington, Idaho, and Oregon) found that, after controlling
for any changes in demographics, sexual behaviors, and increased
sensitivity of clinical tests, there was a remaining 5\% `true' and
unexplained annual increase in chlamydia positivity from 1997-2004 (Fine
et al. 2008). In response to these and other examples of unabated
chlamydia infection in the presence of control programs, Brunham and
Reckart have proposed the arrested immunity hypothesis (Brunham and
Rekart 2008). Under this hypothesis, early detection and treatment of
chlamydia interrupts the development of acquired immunity, making
treated individuals particularly vulnerable to reinfection almost
immediately after treatment. While we have no natural history studies of
chlamydia infection in humans that address the development, duration,
and extent of immunity, there is growing evidence beyond rodent models
and trends in incidence that partial immunity can develop and play a
role. Rodent models of chlamydial infection suggest that a high
proportion are able to resolve their primary infection and are
temporarily resistant to infection. Rodents that then eventually become
reinfected with chlamydia have a shorter duration of disease, lower
pathogen load and decreased inflammatory response (Rank et al. 2003).
However, it has also been shown that treatment early in the course of
infection interrupts the development of this protective immunity (Su et
al. 2002). There is also some indirect evidence in humans. A 2010 review
article acknowledged that in several studies of infection status among
couples, the rates of discordance (i.e.~one partner is infected while
the other is not), are higher for chlamydia than for gonorrhea and that
this discordance increases with age, providing indirect evidence for
some level of protective immunity to chlamydia that increases with age,
likely due to exposure over time. There is little immunity that develops
to gonorrheal infection due to high levels of antigenic variation
(Batteiger et al. 2010). Recent modeling using data from both the UK and
United States has demonstrated that at least some immunity to chlamydia
following natural clearance is necessary to generate observed patterns
in incidence (Omori, Chemaitelly, and Abu-Raddad 2019). These questions
are particularly relevant in the context of expedited partner therapy,
where the goal is to interrupt transmission by treated individuals and
their partners as quickly as possible. However, due to the arrested
immunity of those treated quickly, if the timing of delivery and uptake
of partners is not sufficient, the initially treated is likely at higher
risk of reinfection than under the standard referral scenario. If
sufficient numbers of partners are treated effectively and quickly and
transmission throughout the network is greatly diminished, then EPT may
be able to overcome the effects of this arrested immunity.

\chapter*{Conclusion}\label{conclusion}
\addcontentsline{toc}{chapter}{Conclusion}

We conclude.

\appendix

\chapter{The First Appendix}\label{the-first-appendix}

additional figures?

\chapter{The Second Appendix}\label{the-second-appendix}

more technical stuff in here?

\chapter*{Colophon}\label{colophon}
\addcontentsline{toc}{chapter}{Colophon}

This document is set in \href{https://github.com/georgd/EB-Garamond}{EB
Garamond}, \href{https://github.com/adobe-fonts/source-code-pro/}{Source
Code Pro} and \href{http://www.latofonts.com/lato-free-fonts/}{Lato}.
The body text is set at 11pt with \(\familydefault\).

It was written in R Markdown and \(\LaTeX\), and rendered into PDF using
\href{https://github.com/benmarwick/huskydown}{huskydown} and
\href{https://github.com/rstudio/bookdown}{bookdown}.

This document was typeset using the XeTeX typesetting system, and the
\href{http://staff.washington.edu/fox/tex/}{University of Washington
Thesis class} class created by Jim Fox. Under the hood, the
\href{https://github.com/UWIT-IAM/UWThesis}{University of Washington
Thesis LaTeX template} is used to ensure that documents conform
precisely to submission standards. Other elements of the document
formatting source code have been taken from the
\href{https://github.com/stevenpollack/ucbthesis}{Latex, Knitr, and
RMarkdown templates for UC Berkeley's graduate thesis}, and
\href{https://github.com/suchow/Dissertate}{Dissertate: a LaTeX
dissertation template to support the production and typesetting of a PhD
dissertation at Harvard, Princeton, and NYU}

The source files for this thesis, along with all the data files, have
been organised into an R package, xxx, which is available at
\url{https://github.com/xxx/xxx}. A hard copy of the thesis can be found
in the University of Washington library.

This version of the thesis was generated on 2020-09-28 12:46:24. The
repository is currently at this commit:

The computational environment that was used to generate this version is
as follows:
\begin{verbatim}
- Session info ---------------------------------------------------------------
 setting  value                       
 version  R version 3.6.1 (2019-07-05)
 os       macOS Catalina 10.15.3      
 system   x86_64, darwin15.6.0        
 ui       X11                         
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2020-09-28                  

- Packages -------------------------------------------------------------------
 package        * version    date       lib
 ape              5.3        2019-03-17 [1]
 assertthat       0.2.1      2019-03-21 [1]
 backports        1.1.9      2020-08-24 [1]
 bookdown         0.20.2     2020-08-06 [1]
 broom            0.5.2      2019-04-07 [1]
 callr            3.4.3      2020-03-28 [1]
 cellranger       1.1.0      2016-07-27 [1]
 cli              2.0.2      2020-02-28 [1]
 coda             0.19-3     2019-07-05 [1]
 codetools        0.2-16     2018-12-24 [1]
 colorspace       1.4-1      2019-03-18 [1]
 crayon           1.3.4      2017-09-16 [1]
 data.table       1.12.8     2019-12-09 [1]
 DBI              1.1.0      2019-12-15 [1]
 ddaf           * 0.0.0.9000 2020-09-25 [1]
 DEoptimR         1.0-8      2016-11-19 [1]
 desc             1.2.0      2018-05-01 [1]
 deSolve        * 1.27.1     2020-01-02 [1]
 devtools       * 2.3.1      2020-07-21 [1]
 digest           0.6.25     2020-02-23 [1]
 doParallel       1.0.15     2019-08-02 [1]
 dplyr          * 1.0.2      2020-08-18 [1]
 ellipsis         0.3.1      2020-05-15 [1]
 EpiModel       * 1.7.5      2020-01-07 [1]
 ergm           * 3.10.4     2019-06-10 [1]
 evaluate         0.14       2019-05-28 [1]
 fansi            0.4.1      2020-01-08 [1]
 farver           2.0.3      2020-01-16 [1]
 flexsurv         1.1.1      2019-03-18 [1]
 forcats        * 0.4.0      2019-02-17 [1]
 foreach          1.4.7      2019-07-27 [1]
 fs               1.5.0      2020-07-31 [1]
 generics         0.0.2      2018-11-29 [1]
 ggfortify      * 0.4.7      2019-05-26 [1]
 ggplot2        * 3.3.2      2020-06-19 [1]
 ggpubr         * 0.2.2      2019-08-07 [1]
 ggsignif         0.6.0      2019-08-08 [1]
 ggthemes       * 4.2.0      2019-05-13 [1]
 git2r            0.27.1     2020-05-03 [1]
 glue             1.4.1      2020-05-13 [1]
 gridExtra      * 2.3        2017-09-09 [1]
 gtable           0.3.0      2019-03-25 [1]
 haven            2.1.1      2019-07-04 [1]
 here           * 0.1        2017-05-28 [1]
 hms              0.5.0      2019-07-09 [1]
 htmltools        0.5.0      2020-06-16 [1]
 httr             1.4.2      2020-07-20 [1]
 huskydown      * 0.0.5      2020-08-06 [1]
 iterators        1.0.12     2019-07-26 [1]
 jsonlite         1.7.0      2020-06-25 [1]
 kableExtra     * 1.1.0      2019-03-16 [1]
 km.ci            0.5-2      2009-08-30 [1]
 KMsurv           0.1-5      2012-12-03 [1]
 knitr            1.29       2020-06-23 [1]
 labeling         0.3        2014-08-23 [1]
 lattice          0.20-38    2018-11-04 [1]
 lazyeval         0.2.2      2019-03-15 [1]
 lifecycle        0.2.0      2020-03-06 [1]
 lpSolve          5.6.13.3   2019-08-19 [1]
 lubridate        1.7.4      2018-04-11 [1]
 magrittr       * 1.5        2014-11-22 [1]
 MASS             7.3-51.4   2019-03-31 [1]
 Matrix           1.2-17     2019-03-22 [1]
 memoise          1.1.0      2017-04-21 [1]
 mitools          2.4        2019-04-26 [1]
 modelr           0.1.4      2019-02-18 [1]
 mstate           0.2.11     2018-04-09 [1]
 muhaz            1.2.6.1    2019-01-26 [1]
 munsell          0.5.0      2018-06-12 [1]
 mvtnorm          1.0-11     2019-06-19 [1]
 network        * 1.16.0     2019-12-01 [1]
 networkDynamic * 0.10.0     2019-04-05 [1]
 nlme             3.1-140    2019-05-12 [1]
 pillar           1.4.6      2020-07-10 [1]
 pkgbuild         1.1.0      2020-07-13 [1]
 pkgconfig        2.0.3      2019-09-22 [1]
 pkgload          1.1.0      2020-05-29 [1]
 prettyunits      1.1.1      2020-01-24 [1]
 processx         3.4.3      2020-07-05 [1]
 ps               1.3.4      2020-08-11 [1]
 purrr          * 0.3.4      2020-04-17 [1]
 quadprog         1.5-7      2019-05-06 [1]
 R6               2.4.1      2019-11-12 [1]
 RColorBrewer   * 1.1-2      2014-12-07 [1]
 Rcpp             1.0.5      2020-07-06 [1]
 readr          * 1.3.1      2018-12-21 [1]
 readxl           1.3.1      2019-03-13 [1]
 remotes          2.2.0      2020-07-21 [1]
 rlang            0.4.7      2020-07-09 [1]
 rmarkdown        2.3        2020-06-18 [1]
 robustbase       0.93-5     2019-05-12 [1]
 rprojroot        1.3-2      2018-01-03 [1]
 rstudioapi       0.11       2020-02-07 [1]
 rvest            0.3.4      2019-05-15 [1]
 scales           1.1.1      2020-05-11 [1]
 sessioninfo      1.1.1      2018-11-05 [1]
 srvyr            0.4.0      2020-07-30 [1]
 statnet.common   4.3.0      2019-06-02 [1]
 stringi          1.4.6      2020-02-17 [1]
 stringr        * 1.4.0      2019-02-10 [1]
 survey           4.0        2020-04-03 [1]
 survival         2.44-1.1   2019-04-01 [1]
 survminer      * 0.4.5      2019-08-03 [1]
 survMisc         0.5.5      2018-07-05 [1]
 tergm          * 3.6.1      2019-06-12 [1]
 testthat         2.3.2      2020-03-02 [1]
 tibble         * 3.0.3      2020-07-10 [1]
 tidyr          * 1.1.1      2020-07-31 [1]
 tidyselect       1.1.0      2020-05-11 [1]
 tidyverse      * 1.2.1      2017-11-14 [1]
 trust            0.1-8      2020-01-10 [1]
 usethis        * 1.6.1      2020-04-29 [1]
 vctrs            0.3.2      2020-07-15 [1]
 viridisLite      0.3.0      2018-02-01 [1]
 webshot          0.5.1      2018-09-28 [1]
 withr            2.2.0      2020-04-20 [1]
 xfun             0.16       2020-07-24 [1]
 xml2             1.3.2      2020-04-23 [1]
 xtable           1.8-4      2019-04-21 [1]
 yaml             2.2.1      2020-02-01 [1]
 zoo              1.8-6      2019-05-28 [1]
 source                               
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 Github (rstudio/bookdown@f9cf1ac)    
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.1)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 local                                
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 Github (benmarwick/huskydown@a909835)
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.1)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.1)                       
 CRAN (R 3.6.1)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.1)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.2)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       
 CRAN (R 3.6.0)                       

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
\end{verbatim}
\backmatter

\chapter*{References}\label{references}
\addcontentsline{toc}{chapter}{References}

\markboth{References}{References}

\noindent

\setlength{\parindent}{-0.20in} \setlength{\leftskip}{0.20in}
\setlength{\parskip}{8pt}

\hypertarget{refs}{}
\hypertarget{ref-Singer2006}{}
Singer, M. C., Erickson, P. I., Badiane, L., Diaz, R., Ortiz, D.,
Abraham, T., \& Nicolaysen, A. M. (2006). Syndemics, sex and the city:
Understanding sexually transmitted diseases in social and cultural
context. \emph{Social Science and Medicine}, \emph{63}(8), 2010--2021.
\url{http://doi.org/10.1016/j.socscimed.2006.05.012}
\end{document}
