# Survival Analysis of Relationship Duration {#surv}

* main goal here to understand where in the distribution we may not be capturing when we use models based on a memoryless process, and explore some ways to do better within the constraints of feasibility imposed by epidemic models
* so we primarily use the exponential distribution in the SA analyses
* discuss survey data and censoring / truncation issues
*
And then flesh out the details of the analyses with a clear narrative and you have the core of a chapter!

The duration of sexual relationships across a population generates the network structure largely responsible for either exposing individuals to or protecting individuals from sexually transmitted infections (STIs). In addition to dictating this period of possible exposure, relationship durations relative to the pathogen-specific duration of infection are an important driver of how quickly STIs can spread throughout a population. Transmission beyond a pair of actors for infections with short durations relative to relationship lengths is challenging and slow, and it is more likely that an infection will be detected and treated or resolved naturally prior to the dissolution of the relationship. If the duration of infection and duration of relationships are more equal, there is a greater chance that the infection can spread to future partners and throughout the network. When partnerships overlap, transmission pathways increase even among those individuals with few lifetime partners, and this effect is even greater when the duration of overlap is large (Armbruster, Wang, and Morris 2017; Morris and Kretzschmar 1997).  

The pattern of relationship durations across the life-course is also important because STIs often have distinct age patterns in terms of prevalence. Individual age is often used as a predictor for risky sexual behavior, but there is additional complexity when considering the effect of age on the duration of relationships across the life-course. Young age likely influences the immediate intentions for relationships (i.e. serious or casual), and the frequency at which individuals form new relationships, but somewhat paradoxically it is also true that the only people who can report extremely long relationships are those who started them at young ages. This also introduces complex sampling issues because most data on relationship durations is collected cross-sectionally or retrospectively – not longitudinally.
Given the importance of relationship duration to features of STI epidemiology discussed above, there is growing interest in improving the representation of relational durations in dynamic network models used to study epidemics. This study demonstrates the ways in which the current literature fails to represent this distribution and proposes a new modeling framework to better capture these relationships across the life-course.

One common class of models used to understand network influences on patterns of STI transmission is known as separable temporal exponential-family random graph models (STERGMs). These models are governed by two expressions: one that represents the set of processes that influence the formation of relationships, and a comparable one for dissolution (Krivitsky and Handcock 2014). The current standard practice for the dissolution models in this modeling framework assumes that once a relationship begins, its persistence is governed by a constant hazard. This memoryless process is a convenient simplifying assumption, adopted because most hypotheses being explored relate to processes impacting network formation or cross-sectional structure. However, it is unlikely that this assumption faithfully represents the distribution all relationship durations we observe across a wide range of ages.

Several recent models have begun to address this issue by splitting out relationships into two categories: the first, marriages and cohabitations or main partnerships, and the second, persistent or casual partnerships. These are then modeled as separate networks simultaneously. By structuring the model in this fashion, each network has a hazard of dissolution specific to its type. (These models often have a third network for one-time sexual contacts which last only one time-step, but this network is not the focus of our study). While these models are indeed able to reproduce the mean relationship lengths drawn from empirical data, it remains unknown how well these strategies reproduce the full distribution of lengths observed. In particular, the memoryless assumption means that the modal length of main partnerships remains near zero across all ages, which basic intuition says is not true and descriptive data analysis confirms. Other work has considered disaggregating relational durations by a single demographic attribute of their members related to a hypothesis or prevention modality being explored, but again with no further effort to capture the full distribution, particularly by age (Goodreau et al. 2017; Jenness et al. 2017).

In this ongoing study, we seek to understand the changing distribution of relationship duration over the life-course using data from the National Survey of Family Growth, to evaluate which features the above dissolution assumptions are capable of replicating and which they cannot.  We then introduce an alternative framework designed to more faithfully represent these data and the different demographic and data-collection processes that impact them in an age-structured population over time. We use tools from both event history analysis and network analysis to answer the following questions: First, under what circumstances, if any, can an exponentially distributed time-to-event model reasonably approximate empirical relationship duration data? Second, does it make sense to lump marriages and cohabitations into one network with the same dissolution probability? And third, can we better capture the age-wise relationship distribution by using one network where (1) relationships can transition between states (e.g. from a cohabitation into a marriage) rather than modeling several types separately, and (2) where relational formation probabilities depend on current relational status.

**Data**  
The empirical data used in this study are drawn from the 2006-2010 and 2011-2015 waves of the National Survey of Family Growth (NSFG). The NSFG surveys men and women aged 15-44 on many aspects of family life, including but not limited to marriage and divorce, pregnancy, contraception use, infertility, and other aspects of sexual and reproductive behavior. In addition to the demographic information recorded for each respondent and their sampling weights, in this study we use the data collected in section C of the public use files on each respondent’s recent sexual partnerships with opposite-sex partners in the last year, with a maximum of three partnerships reported. These data include the century-month of first sexual contact, the century-month of last sexual contact, whether the respondent considers this sexual partnership to be ongoing, and the partnership status (marriage, cohabitation, or other). We limit the combined data set to those respondents who report at least one partnership in the last year. Out of the original 43,303 respondents, our subset contains 32,516 respondents who report on 40,443 sexual partnerships. Due to the study design, all relationships that respondents report as ongoing on the day of interview have right-censored relationship lengths, and there is left-truncation present due to the large number or relationships that started prior to the observation window but continued into it.

**Methods**  
First the empirical relational duration data (using the start and end dates of all reported relationships in NSFG) will be investigated using histograms (overall and stratified by age category). Then, due to the issues of right censoring and left truncation as a result of survey design in NSFG, a reference survival curve will be constructed from the empirical data using a Modified Kaplan-Meier model following (Burington et al. 2010) and using the R package ‘survival’. Next, exploratory parametric models will be estimated from the data (with corrections for right-censoring and left-truncation) using a variety of distributions (namely and latent mixture components) to gain intuition about the underlying generative processes. Initial models will be covariate-free (representing the effects of relationship duration only on the chances of survival) and additional models will begin to examine the influence of age on relationship duration, including (but not limited to) the ego’s age category, the reported current age difference between ego and alter, and the ego’s age category at the beginning of each reported relationship. All models without latent components will be fit using the R package ‘flexsurv’ and the likelihood functions for all models with latent components will be personally developed and models will be fit using the maxLik package (Jackson 2016; Henningsen and Toomet 2011).

From PAA abstract: In our preliminary work, we first checked the assumption that relationship duration can be modeled by a simple memoryless process, and then explored some natural extensions to this framework. In order to generate the reference distribution, we fit a Kaplan-Meier model using a modified estimator to account for both right-censoring and left-truncation following Burington et al (2010). We then fit several parametric models (all adjusted for the above sampling issues): first a simple exponential model to represent the memoryless process assumption, then a Weibull distribution and Gamma distribution, all with and without additional covariate attributes. Model fit was evaluated primarily using the Akaike Information Criterion (AIC) and visuals to understand which relationship lengths were represented better than others, given our ultimate goal of adapting these into dynamic network simulations. Below is a selection of explored models; parametric models with covariate categories are displayed in color, with their Kaplan-Meier reference curves plotted in black. All parameters in these fitted models are statistically significant (p < 0.001).  

**Results**  

The first takeaway is that an exponential distribution alone is not sufficient to capture the relationship distribution – it overestimates the survival of short relationships and underestimates the survival of long relationships (top left figure, below). The Weibull and Gamma perform better and capture more of the short relationships, suggesting that there is important heterogeneity in the data, but like the first models they also fail to capture the longest relationships. The age category of the reporting individual is not explanatory across all age categories (top right). This is perhaps not surprising, in that the age distribution of relationship lengths is at least partly an emergent property rather than a causal one. That is, no individual can have a relationship that has lasted longer than they have been sexually active, so the range of relationship lengths for young age categories is relatively small. Meanwhile, the older age categories are challenging to represent because the possible range of relationships is so much larger, and are likely influenced not only by dissolution probabilities but also by the changing formation probabilities over the lifecourse – that is, older people in long-term relationships do not start new relationships at the same rate as others, and thus have relatively few relationships that are short.  

The next two models test how appropriate it is to group relationships defined as marriages and cohabitations into the same dissolution model, as has been done in recent STERGMs. We see clear evidence that marriages and cohabitations have distinct hazards of dissolution and the combined marriage and cohabitation curve, like the simple exponential for all relationships, dramatically fails to capture both the shortest and longest relationships of these types (bottom right and bottom left figures, respectively. These results are similar to other work in family demography that has shown significant differences in the risk of dissolution between cohabitations and marriages due to variation in joint lifestyles (van Houdt and Poortman 2018). These results suggest to us that previously developed STERGM dissolution models that only capture the mean relationship length are not appropriate approximations of the data, and that cohabitation represents a distinctly separate type of relationship from marriages and other casual relationships and should be treated as such in our networks.  
