# Chlamydia, Acquired Immunity, & Expedited Partner Therapy? {#ept}

copying over some text from diss proposal:  

C. trachomatis is an obligate intracellular bacterium transmitted through sexual contact among humans.  Chlamydial infections are most often asymptomatic. Untreated infections in women are an additional public health concern because they can lead to a variety of sequalae including pelvic inflammatory disease, scarring of ovaries and fallopian tubes, ectopic pregnancies, chronic pain, and infertility. Repeat infections are common and are an additional risk factor for the development of the above sequelae (Brunham and Rey-Ladino 2005). There is a great deal of uncertainty regarding the natural history of chlamydia, but the duration of infection for untreated individuals is generally thought to be up to 6 months for men and a year or more for women (Golden et al. 2000; Satterwhite et al. 2013). Chlamydia is usually treated with azithromycin or doxycycline, and unlike other common STIs like syphilis and gonorrhea, true antibiotic resistance is rare (Kong et al. 2015).  

Chlamydia is the most common reportable disease in the United States and incidence, particularly adolescents and young adults aged 15-29, is increasing nationwide. The Centers for Disease Control and Prevention (CDC) estimates that half of all new STI infections (including gonorrhea, syphilis, and others) occur in those aged 15-24 despite them making up only a quarter of the sexually active population. Even in places like King County, Washington, where overall rates have remained stable, longstanding acknowledged disparities in prevalence by race are marked and continue to increase (2015 SKCPH STD Report). These rates are particularly distressing in light of the fertility consequences of long-term infection and reinfection: it is estimated that in King County, over 60% of non-Hispanic Black women have had at least one chlamydia infection by age 34 (a rate 5x higher than non-Hispanic White women) and 1 in 500 of non-Hispanic Black women develops chlamydia-associated tubal factor infertility over their life-course (Chambers et al. 2018).

The United States has some of the highest STD rates in the industrialized world, and despite this, funding for public health programs dedicated to these issues has largely declined (CDC 2016 STD Report). As a result, few health departments are able to offer traditional partner notification services, where a patient who tests positive for an STI gives the contact information of their recent sex partners to the health department, and the department then contacts their partners with the hope that these partners will then get tested and, if necessary, treated. Expedited partner therapy (EPT) was developed with this scenario in mind (See figure 2). Under EPT, a patient who tests positive, upon receipt of their own treatment, receives either additional antibiotic pills for their recent sexual partners or prescriptions for treatment that their partners can fill. The patient then is expected to hand-deliver either the treatment or prescription to their partner(s), who take the medicine at their own discretion and without the need for a positive lab test. By using these actors to essentially leverage their sexual network in reverse, this system hopes to decrease the time to treatment for all possible infected partners and increase the total number of partners treated. It can also reduce re-infection among the index patients if the partnerships are ongoing.
There have been several clinical trials of EPT across the US (and Europe), including Washington State.  These trails demonstrated that relative to traditional referral practices, EPT provision increased the proportion of partners who were ultimately treated, reduced the number of individuals who were re-infected at follow-up, and was less costly if at least 30% of partners were treated via EPT (CITE). Despite these results and a growing body of evidence in support, widespread implementation of EPT has been slow and there are still many questions to be answered.


also -- EPT as a tool for health equity, not just effective population-level decrease in prevalence -- can be more effective in high-prevalance groups?

Annals of Internal Medicine Article High Incidence of New Sexually Transmitted Infections in the Year
following a Sexually Transmitted Infection: A Case for Rescreening - Peterman et al


Arrested Immunity Hypothesis
	One of the paradoxes in era of modern public health is that chlamydia incidence has actually increased overall in the presence of mass control programs. In Sweden, Norway, Finland and Canada the rates initially decreased but then resumed increasing, and in Australia, United States, and the United Kingdom the rates never stopped increasing even after program initiation, although this second pattern has been attributed to the challenges of implementing control programs consistently throughout a large population  (Brunham and Rekart 2008).  These areas now experience incidence rates higher than rates prior to introduction of control programs. Additionally, a regression analysis using data from family planning clinics in Region X of the United States (Alaska, Washington, Idaho, and Oregon) found that, after controlling for any changes in demographics, sexual behaviors, and increased sensitivity of clinical tests, there was a remaining 5% ‘true’ and unexplained annual increase in chlamydia positivity from 1997-2004 (Fine et al. 2008). In response to these and other examples of unabated chlamydia infection in the presence of control programs, Brunham and Reckart have proposed the arrested immunity hypothesis (Brunham and Rekart 2008). Under this hypothesis, early detection and treatment of chlamydia interrupts the development of acquired immunity, making treated individuals particularly vulnerable to reinfection almost immediately after treatment.
While we have no natural history studies of chlamydia infection in humans that address the development, duration, and extent of immunity, there is growing evidence beyond rodent models and trends in incidence that partial immunity can develop and play a role. 	Rodent models of chlamydial infection suggest that a high proportion are able to resolve their primary infection and are temporarily resistant to infection. Rodents that then eventually become reinfected with chlamydia have a shorter duration of disease, lower pathogen load and decreased inflammatory response (Rank et al. 2003). However, it has also been shown that treatment early in the course of infection interrupts the development of this protective immunity (Su et al. 2002).
There is also some indirect evidence in humans. A 2010 review article acknowledged that in several studies of infection status among couples, the rates of discordance (i.e. one partner is infected while the other is not), are higher for chlamydia than for gonorrhea and that this discordance increases with age, providing indirect evidence for some level of protective immunity to chlamydia that increases with age, likely due to exposure over time. There is little immunity that develops to gonorrheal infection due to high levels of antigenic variation (Batteiger et al. 2010). Recent modeling using data from both the UK and United States has demonstrated that at least some immunity to chlamydia following natural clearance is necessary to generate observed patterns in incidence (Omori, Chemaitelly, and Abu-Raddad 2019).
These questions are particularly relevant in the context of expedited partner therapy, where the goal is to interrupt transmission by treated individuals and their partners as quickly as possible. However, due to the arrested immunity of those treated quickly, if the timing of delivery and uptake of partners is not sufficient, the initially treated is likely at higher risk of reinfection than under the standard referral scenario. If sufficient numbers of partners are treated effectively and quickly and transmission throughout the network is greatly diminished, then EPT may be able to overcome the effects of this arrested immunity.
